stages:
  - build

build-job:
  stage: build
  tags:
    - docker
  image: python:3.11-alpine
  script:
    - python -m pip install -r Api/requirements.txt
    - mkdir -p build/api build/web
    - cp -r Api/* build/api/
    - cp -r Web/* build/web/
    - python -m compileall build/api
